name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build APK
#      run: ./gradlew assembleDebug
      run: ./gradlew assembleRelease

#    - name: Restore Keystore
#      run: |
#        echo "${{ secrets.RELEASE_KEYSTORE

    - name: Sign App APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_2 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
#        path: app/build/outputs/apk/debug/app-debug.apk
        path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
      # ID used to access action output
#
    - name: Deploy to Alpha
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: "${{ secrets.SERVICE_ACCOUNT_JSON }}"
        packageName: com.pecawolf.smstickethelper
        track: alpha
        releaseFiles: app/app-mouedu-release.apk
