name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

      - name: Sign App APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        # ID used to access action output

      - name: Build with Gradle
        run: ./gradlew buildRelease

    - name: Deploy to Alpha
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        packageName: com.c4p.smartcongress2
        track: alpha
        releaseFiles: app/mouedu/release/app-mouedu-release.apk
